name: RealTime
version: 3.1
description: 'Shows user''s real time based on their IP'
author: Trojmans
main: nl.trojmans.realtime.RealTime
softdepend: [ProtocolLib]

commands:
    realtimereloadconfig:
        description: reloading the config RealTime
        usage: /<command>